name: Build

on: [push, pull_request]

jobs:
    windows:
        runs-on: windows-2022

        steps:
        - uses: actions/checkout@v2
        - uses: open-watcom/setup-watcom@v0
        - env:
          LIB386_PATH: "$GITHUB_WORKSPACE\\LIB386"
          INCLUDE: "$LIB386_PATH;$INCLUDE"
        - run: |
            cd "$GITHUB_WORKSPACE/LIB386/LIB_3D"
            wmake
            cd "$GITHUB_WORKSPACE/LIB386/LIB_CD"
            wmake
            cd "$GITHUB_WORKSPACE/LIB386/LIB_MENU"
            wmake
            cd "$GITHUB_WORKSPACE/LIB386/LIB_MIDI"
            wmake
            cd "$GITHUB_WORKSPACE/LIB386/LIB_MIX"
            wmake
            cd "$GITHUB_WORKSPACE/LIB386/LIB_SAMP"
            wmake
            cd "$GITHUB_WORKSPACE/LIB386/LIB_SVGA"
            wmake
            cd "$GITHUB_WORKSPACE/LIB386/LIB_SYS"
            wmake
            cd "$GITHUB_WORKSPACE/SOURCES"
            wmake
            link

        - name: Upload the build artifacts
          uses: actions/upload-artifact@v2
          with:
            name: lba1
            path: SOURCES/LBA0.exe
